datasets:
  - name: movies
    type: csv
    file_path: data/movies.csv
  - name: links
    type: csv
    file_path: data/links.csv
  - name: tmdb
    type: json
    file_path: data/tmdb_cache.json
    
transformations:
  - name: process_movies_and_links
    type: merge
    left_dataset: movies
    right_dataset: links
    join_on: movieId
    how: inner
    target_table: movies
    
  - name: process_tmdb_cache
    type: custom_python
    function: process_tmdb
    input_dataset: tmdb
    target_table: tmdb_data

views:
  - name: movies_enriched_view
    sql_file: config/sql/movies_enriched_view.sql

